### ISSUE TITLE
9

### ISSUE THREAD

**Issue by sasholy** [dwisiswant0/gf-secrets#3]

**Comment by dwisiswant0** [comment]
You can use [meg](https://github.com/tomnomnom/meg) or [katana](https://github.com/projectdiscovery/katana) instead of fff.

> [...] which JSON patterns?

From _/path/to/gf-secrets/.gf_ to _$HOME/.gf_.

**Comment by sasholy** [comment]
> Вы можете использовать [мэг](https://github.com/tomnomnom/meg) или [катану](https://github.com/projectdiscovery/katana) вместо ффф.
> 
> > [...] какие шаблоны JSON?
> 
> Из _/path/to/gf-secrets/.gf_ в _$HOME/.gf_ .

sort -u urls.txt | katana > n.txt
or better
sort -u urls.txt | httpx -mc 200 -silent  | katana > n.txt - ?

special thanks for secpat2gf
